#ifndef CONTEXT_AWARE_IDS_EWMA_MONITOR_HPP_
#define CONTEXT_AWARE_IDS_EWMA_MONITOR_HPP_

#include <Eigen/Dense>
#include <cmath>

namespace context_aware_ids
{
template <size_t DOF>
class EWMAMonitor
{
public:
    using MeasurementVector = Eigen::Matrix <double, DOF, 1>;

    /**
     * @brief Constructor to initialize the statistical bounds
     * @param alpha Smoothing factor
     * @param base_limit Threshold for the empty arm
     * @param mass_limit Extra alowable variance in the payload mass
     */
    EWMAMonitor(double alpha, double base_limit, double mass_limit)
    // Member Initializer Lists (Directly writes values in raw memory)
    // if put inside {} it would slow, as it will create empty first then assign values
    : alpha_(alpha),
    base_limit_(base_limit),
    loaded_limit_(base_limit + mass_limit)
    {
        Sk_.setZero();      // Running average to zerp
    }

    /**
     * @brief Evaluates the EKF residual against the context-aware threshold.
     * @param residual The truth-gap vector generated by the EKF.
     * @param payload_context 0 for empty arm, 1 for loaded arm.
     * @return TRUE an attack is detected. FALSE if healthy.
     */
    [[nodiscard]] inline bool evaluate_anomaly(const MeasurementVector& residual, int payload_context)
    {
        Sk_ = (alpha_ * residual) + ((1.0 - alpha_) * Sk_);   // EWMA Smoothing
        double curr_limit = (payload_context == 1) ? loaded_limit_ : base_limit_;   // Context Switching
        // THE ALARM
        if (Sk_.norm() > curr_limit)     // L2 Norm of 7-joint error vector.
        {
            return true;    // Blow alarm
        }
        return false;       // Normal operations
    }
private:
    double alpha_;             // Weight given to the newest data (alpha)
    double base_limit_;          // Threshold for bare manipulator (Th_0)
    double loaded_limit_;       // Threshold for loaded manipulator (Th_1)
    MeasurementVector Sk_;      // The smoothed error vector in fast memory


};
} // namespace context_aware_ids
#endif // CONTEXT_AWARE_IDS_EWMA_MONITOR_HPP_